apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jobs-pods-reader
  labels:
    {{- include "otus-2.labels" . | nindent 4 }}
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jobs-pods-reader
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: jobs-pods-reader # this must match the name of the Role or ClusterRole you wish to bind to  
  apiGroup: rbac.authorization.k8s.io