apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: otus-2
  name: jobs-pods-reader
rules:
  - apiGroups: ["", "batch"] # "" indicates the core API group
    resources: ["jobs", "pods"]
    verbs: ["get", "watch", "list"]
    
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs-pods-reader
  namespace: otus-2
  
---

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jobs-pods-reader
  namespace: otus-2
subjects:
  # You can specify more than one "subject"
  - kind: ServiceAccount
    name: jobs-pods-reader
    namespace: otus-2
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: jobs-pods-reader # this must match the name of the Role or ClusterRole you wish to bind to  
  apiGroup: rbac.authorization.k8s.io